/* This file was generated by SableCC (http://www.sablecc.org/). */

package expression.node;

import expression.analysis.*;

@SuppressWarnings("nls")
public final class ACaractereTipo extends PTipo
{
    private TNCaractere _nCaractere_;

    public ACaractereTipo()
    {
        // Constructor
    }

    public ACaractereTipo(
        @SuppressWarnings("hiding") TNCaractere _nCaractere_)
    {
        // Constructor
        setNCaractere(_nCaractere_);

    }

    @Override
    public Object clone()
    {
        return new ACaractereTipo(
            cloneNode(this._nCaractere_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACaractereTipo(this);
    }

    public TNCaractere getNCaractere()
    {
        return this._nCaractere_;
    }

    public void setNCaractere(TNCaractere node)
    {
        if(this._nCaractere_ != null)
        {
            this._nCaractere_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nCaractere_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nCaractere_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nCaractere_ == child)
        {
            this._nCaractere_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nCaractere_ == oldChild)
        {
            setNCaractere((TNCaractere) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
