/* This file was generated by SableCC (http://www.sablecc.org/). */

package expression.node;

import expression.analysis.*;

@SuppressWarnings("nls")
public final class AEnquantoComando extends PComando
{
    private PEnquantoEstruturas _enquantoEstruturas_;

    public AEnquantoComando()
    {
        // Constructor
    }

    public AEnquantoComando(
        @SuppressWarnings("hiding") PEnquantoEstruturas _enquantoEstruturas_)
    {
        // Constructor
        setEnquantoEstruturas(_enquantoEstruturas_);

    }

    @Override
    public Object clone()
    {
        return new AEnquantoComando(
            cloneNode(this._enquantoEstruturas_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEnquantoComando(this);
    }

    public PEnquantoEstruturas getEnquantoEstruturas()
    {
        return this._enquantoEstruturas_;
    }

    public void setEnquantoEstruturas(PEnquantoEstruturas node)
    {
        if(this._enquantoEstruturas_ != null)
        {
            this._enquantoEstruturas_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._enquantoEstruturas_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._enquantoEstruturas_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._enquantoEstruturas_ == child)
        {
            this._enquantoEstruturas_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._enquantoEstruturas_ == oldChild)
        {
            setEnquantoEstruturas((PEnquantoEstruturas) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
