/* This file was generated by SableCC (http://www.sablecc.org/). */

package expression.node;

import expression.analysis.*;

@SuppressWarnings("nls")
public final class AExpressaoLogicaExpressaoLogica extends PExpressaoLogica
{
    private PParenteses _parenteses_;
    private PSinalLogicoOu _sinalLogicoOu_;
    private PParenteses2 _parenteses2_;

    public AExpressaoLogicaExpressaoLogica()
    {
        // Constructor
    }

    public AExpressaoLogicaExpressaoLogica(
        @SuppressWarnings("hiding") PParenteses _parenteses_,
        @SuppressWarnings("hiding") PSinalLogicoOu _sinalLogicoOu_,
        @SuppressWarnings("hiding") PParenteses2 _parenteses2_)
    {
        // Constructor
        setParenteses(_parenteses_);

        setSinalLogicoOu(_sinalLogicoOu_);

        setParenteses2(_parenteses2_);

    }

    @Override
    public Object clone()
    {
        return new AExpressaoLogicaExpressaoLogica(
            cloneNode(this._parenteses_),
            cloneNode(this._sinalLogicoOu_),
            cloneNode(this._parenteses2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpressaoLogicaExpressaoLogica(this);
    }

    public PParenteses getParenteses()
    {
        return this._parenteses_;
    }

    public void setParenteses(PParenteses node)
    {
        if(this._parenteses_ != null)
        {
            this._parenteses_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parenteses_ = node;
    }

    public PSinalLogicoOu getSinalLogicoOu()
    {
        return this._sinalLogicoOu_;
    }

    public void setSinalLogicoOu(PSinalLogicoOu node)
    {
        if(this._sinalLogicoOu_ != null)
        {
            this._sinalLogicoOu_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sinalLogicoOu_ = node;
    }

    public PParenteses2 getParenteses2()
    {
        return this._parenteses2_;
    }

    public void setParenteses2(PParenteses2 node)
    {
        if(this._parenteses2_ != null)
        {
            this._parenteses2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parenteses2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parenteses_)
            + toString(this._sinalLogicoOu_)
            + toString(this._parenteses2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parenteses_ == child)
        {
            this._parenteses_ = null;
            return;
        }

        if(this._sinalLogicoOu_ == child)
        {
            this._sinalLogicoOu_ = null;
            return;
        }

        if(this._parenteses2_ == child)
        {
            this._parenteses2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._parenteses_ == oldChild)
        {
            setParenteses((PParenteses) newChild);
            return;
        }

        if(this._sinalLogicoOu_ == oldChild)
        {
            setSinalLogicoOu((PSinalLogicoOu) newChild);
            return;
        }

        if(this._parenteses2_ == oldChild)
        {
            setParenteses2((PParenteses2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
