/* This file was generated by SableCC (http://www.sablecc.org/). */

package expression.node;

import expression.analysis.*;

@SuppressWarnings("nls")
public final class AExpressaoRelacionalTermoLogico extends PTermoLogico
{
    private PExpressaoRelac _expressaoRelac_;

    public AExpressaoRelacionalTermoLogico()
    {
        // Constructor
    }

    public AExpressaoRelacionalTermoLogico(
        @SuppressWarnings("hiding") PExpressaoRelac _expressaoRelac_)
    {
        // Constructor
        setExpressaoRelac(_expressaoRelac_);

    }

    @Override
    public Object clone()
    {
        return new AExpressaoRelacionalTermoLogico(
            cloneNode(this._expressaoRelac_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpressaoRelacionalTermoLogico(this);
    }

    public PExpressaoRelac getExpressaoRelac()
    {
        return this._expressaoRelac_;
    }

    public void setExpressaoRelac(PExpressaoRelac node)
    {
        if(this._expressaoRelac_ != null)
        {
            this._expressaoRelac_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoRelac_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressaoRelac_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressaoRelac_ == child)
        {
            this._expressaoRelac_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressaoRelac_ == oldChild)
        {
            setExpressaoRelac((PExpressaoRelac) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
