/* This file was generated by SableCC (http://www.sablecc.org/). */

package expression.node;

import expression.analysis.*;

@SuppressWarnings("nls")
public final class AExpressaoLogicaExpressaoLogica extends PExpressaoLogica
{
    private PSinalLogicoOu _sinalLogicoOu_;
    private PTermoLogico _termoLogico_;

    public AExpressaoLogicaExpressaoLogica()
    {
        // Constructor
    }

    public AExpressaoLogicaExpressaoLogica(
        @SuppressWarnings("hiding") PSinalLogicoOu _sinalLogicoOu_,
        @SuppressWarnings("hiding") PTermoLogico _termoLogico_)
    {
        // Constructor
        setSinalLogicoOu(_sinalLogicoOu_);

        setTermoLogico(_termoLogico_);

    }

    @Override
    public Object clone()
    {
        return new AExpressaoLogicaExpressaoLogica(
            cloneNode(this._sinalLogicoOu_),
            cloneNode(this._termoLogico_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpressaoLogicaExpressaoLogica(this);
    }

    public PSinalLogicoOu getSinalLogicoOu()
    {
        return this._sinalLogicoOu_;
    }

    public void setSinalLogicoOu(PSinalLogicoOu node)
    {
        if(this._sinalLogicoOu_ != null)
        {
            this._sinalLogicoOu_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sinalLogicoOu_ = node;
    }

    public PTermoLogico getTermoLogico()
    {
        return this._termoLogico_;
    }

    public void setTermoLogico(PTermoLogico node)
    {
        if(this._termoLogico_ != null)
        {
            this._termoLogico_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoLogico_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sinalLogicoOu_)
            + toString(this._termoLogico_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sinalLogicoOu_ == child)
        {
            this._sinalLogicoOu_ = null;
            return;
        }

        if(this._termoLogico_ == child)
        {
            this._termoLogico_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sinalLogicoOu_ == oldChild)
        {
            setSinalLogicoOu((PSinalLogicoOu) newChild);
            return;
        }

        if(this._termoLogico_ == oldChild)
        {
            setTermoLogico((PTermoLogico) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
