/* This file was generated by SableCC (http://www.sablecc.org/). */

package expression.node;

import expression.analysis.*;

@SuppressWarnings("nls")
public final class ANegacaoNegacao extends PNegacao
{
    private PSinalLogicoNao _sinalLogicoNao_;
    private PParenteses _parenteses_;

    public ANegacaoNegacao()
    {
        // Constructor
    }

    public ANegacaoNegacao(
        @SuppressWarnings("hiding") PSinalLogicoNao _sinalLogicoNao_,
        @SuppressWarnings("hiding") PParenteses _parenteses_)
    {
        // Constructor
        setSinalLogicoNao(_sinalLogicoNao_);

        setParenteses(_parenteses_);

    }

    @Override
    public Object clone()
    {
        return new ANegacaoNegacao(
            cloneNode(this._sinalLogicoNao_),
            cloneNode(this._parenteses_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANegacaoNegacao(this);
    }

    public PSinalLogicoNao getSinalLogicoNao()
    {
        return this._sinalLogicoNao_;
    }

    public void setSinalLogicoNao(PSinalLogicoNao node)
    {
        if(this._sinalLogicoNao_ != null)
        {
            this._sinalLogicoNao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sinalLogicoNao_ = node;
    }

    public PParenteses getParenteses()
    {
        return this._parenteses_;
    }

    public void setParenteses(PParenteses node)
    {
        if(this._parenteses_ != null)
        {
            this._parenteses_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parenteses_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sinalLogicoNao_)
            + toString(this._parenteses_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sinalLogicoNao_ == child)
        {
            this._sinalLogicoNao_ = null;
            return;
        }

        if(this._parenteses_ == child)
        {
            this._parenteses_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sinalLogicoNao_ == oldChild)
        {
            setSinalLogicoNao((PSinalLogicoNao) newChild);
            return;
        }

        if(this._parenteses_ == oldChild)
        {
            setParenteses((PParenteses) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
