/* This file was generated by SableCC (http://www.sablecc.org/). */

package expression.node;

import expression.analysis.*;

@SuppressWarnings("nls")
public final class AParentesesParenteses2 extends PParenteses2
{
    private PParenteses _parenteses_;

    public AParentesesParenteses2()
    {
        // Constructor
    }

    public AParentesesParenteses2(
        @SuppressWarnings("hiding") PParenteses _parenteses_)
    {
        // Constructor
        setParenteses(_parenteses_);

    }

    @Override
    public Object clone()
    {
        return new AParentesesParenteses2(
            cloneNode(this._parenteses_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParentesesParenteses2(this);
    }

    public PParenteses getParenteses()
    {
        return this._parenteses_;
    }

    public void setParenteses(PParenteses node)
    {
        if(this._parenteses_ != null)
        {
            this._parenteses_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parenteses_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parenteses_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parenteses_ == child)
        {
            this._parenteses_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._parenteses_ == oldChild)
        {
            setParenteses((PParenteses) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
