/* This file was generated by SableCC (http://www.sablecc.org/). */

package expression.node;

import java.util.*;
import expression.analysis.*;

@SuppressWarnings("nls")
public final class AParaEstruturas extends PParaEstruturas
{
    private PVariavel _variavel_;
    private final LinkedList<PComando> _blocoComando_ = new LinkedList<PComando>();

    public AParaEstruturas()
    {
        // Constructor
    }

    public AParaEstruturas(
        @SuppressWarnings("hiding") PVariavel _variavel_,
        @SuppressWarnings("hiding") List<?> _blocoComando_)
    {
        // Constructor
        setVariavel(_variavel_);

        setBlocoComando(_blocoComando_);

    }

    @Override
    public Object clone()
    {
        return new AParaEstruturas(
            cloneNode(this._variavel_),
            cloneList(this._blocoComando_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParaEstruturas(this);
    }

    public PVariavel getVariavel()
    {
        return this._variavel_;
    }

    public void setVariavel(PVariavel node)
    {
        if(this._variavel_ != null)
        {
            this._variavel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variavel_ = node;
    }

    public LinkedList<PComando> getBlocoComando()
    {
        return this._blocoComando_;
    }

    public void setBlocoComando(List<?> list)
    {
        for(PComando e : this._blocoComando_)
        {
            e.parent(null);
        }
        this._blocoComando_.clear();

        for(Object obj_e : list)
        {
            PComando e = (PComando) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._blocoComando_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._variavel_)
            + toString(this._blocoComando_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._variavel_ == child)
        {
            this._variavel_ = null;
            return;
        }

        if(this._blocoComando_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._variavel_ == oldChild)
        {
            setVariavel((PVariavel) newChild);
            return;
        }

        for(ListIterator<PComando> i = this._blocoComando_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PComando) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
