/* This file was generated by SableCC (http://www.sablecc.org/). */

package expression.node;

import expression.analysis.*;

@SuppressWarnings("nls")
public final class ASeNaoComando extends PComando
{
    private PSeEstruturasNao _seEstruturasNao_;

    public ASeNaoComando()
    {
        // Constructor
    }

    public ASeNaoComando(
        @SuppressWarnings("hiding") PSeEstruturasNao _seEstruturasNao_)
    {
        // Constructor
        setSeEstruturasNao(_seEstruturasNao_);

    }

    @Override
    public Object clone()
    {
        return new ASeNaoComando(
            cloneNode(this._seEstruturasNao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASeNaoComando(this);
    }

    public PSeEstruturasNao getSeEstruturasNao()
    {
        return this._seEstruturasNao_;
    }

    public void setSeEstruturasNao(PSeEstruturasNao node)
    {
        if(this._seEstruturasNao_ != null)
        {
            this._seEstruturasNao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._seEstruturasNao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._seEstruturasNao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._seEstruturasNao_ == child)
        {
            this._seEstruturasNao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._seEstruturasNao_ == oldChild)
        {
            setSeEstruturasNao((PSeEstruturasNao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
