/* This file was generated by SableCC (http://www.sablecc.org/). */

package expression.node;

import expression.analysis.*;

@SuppressWarnings("nls")
public final class ASeSenaoEstruturas extends PSeSenaoEstruturas
{
    private PSeStant _seStant_;
    private PSenaoEstruturas _senaoEstruturas_;

    public ASeSenaoEstruturas()
    {
        // Constructor
    }

    public ASeSenaoEstruturas(
        @SuppressWarnings("hiding") PSeStant _seStant_,
        @SuppressWarnings("hiding") PSenaoEstruturas _senaoEstruturas_)
    {
        // Constructor
        setSeStant(_seStant_);

        setSenaoEstruturas(_senaoEstruturas_);

    }

    @Override
    public Object clone()
    {
        return new ASeSenaoEstruturas(
            cloneNode(this._seStant_),
            cloneNode(this._senaoEstruturas_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASeSenaoEstruturas(this);
    }

    public PSeStant getSeStant()
    {
        return this._seStant_;
    }

    public void setSeStant(PSeStant node)
    {
        if(this._seStant_ != null)
        {
            this._seStant_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._seStant_ = node;
    }

    public PSenaoEstruturas getSenaoEstruturas()
    {
        return this._senaoEstruturas_;
    }

    public void setSenaoEstruturas(PSenaoEstruturas node)
    {
        if(this._senaoEstruturas_ != null)
        {
            this._senaoEstruturas_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._senaoEstruturas_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._seStant_)
            + toString(this._senaoEstruturas_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._seStant_ == child)
        {
            this._seStant_ = null;
            return;
        }

        if(this._senaoEstruturas_ == child)
        {
            this._senaoEstruturas_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._seStant_ == oldChild)
        {
            setSeStant((PSeStant) newChild);
            return;
        }

        if(this._senaoEstruturas_ == oldChild)
        {
            setSenaoEstruturas((PSenaoEstruturas) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
