/* This file was generated by SableCC (http://www.sablecc.org/). */

package expression.node;

import expression.analysis.*;

@SuppressWarnings("nls")
public final class ASomasExpressao2 extends PExpressao2
{
    private PExpressao2 _expressao2_;
    private PSoma _soma_;
    private PTermo2 _termo2_;

    public ASomasExpressao2()
    {
        // Constructor
    }

    public ASomasExpressao2(
        @SuppressWarnings("hiding") PExpressao2 _expressao2_,
        @SuppressWarnings("hiding") PSoma _soma_,
        @SuppressWarnings("hiding") PTermo2 _termo2_)
    {
        // Constructor
        setExpressao2(_expressao2_);

        setSoma(_soma_);

        setTermo2(_termo2_);

    }

    @Override
    public Object clone()
    {
        return new ASomasExpressao2(
            cloneNode(this._expressao2_),
            cloneNode(this._soma_),
            cloneNode(this._termo2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASomasExpressao2(this);
    }

    public PExpressao2 getExpressao2()
    {
        return this._expressao2_;
    }

    public void setExpressao2(PExpressao2 node)
    {
        if(this._expressao2_ != null)
        {
            this._expressao2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressao2_ = node;
    }

    public PSoma getSoma()
    {
        return this._soma_;
    }

    public void setSoma(PSoma node)
    {
        if(this._soma_ != null)
        {
            this._soma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._soma_ = node;
    }

    public PTermo2 getTermo2()
    {
        return this._termo2_;
    }

    public void setTermo2(PTermo2 node)
    {
        if(this._termo2_ != null)
        {
            this._termo2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termo2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressao2_)
            + toString(this._soma_)
            + toString(this._termo2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressao2_ == child)
        {
            this._expressao2_ = null;
            return;
        }

        if(this._soma_ == child)
        {
            this._soma_ = null;
            return;
        }

        if(this._termo2_ == child)
        {
            this._termo2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressao2_ == oldChild)
        {
            setExpressao2((PExpressao2) newChild);
            return;
        }

        if(this._soma_ == oldChild)
        {
            setSoma((PSoma) newChild);
            return;
        }

        if(this._termo2_ == oldChild)
        {
            setTermo2((PTermo2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
