/* This file was generated by SableCC (http://www.sablecc.org/). */

package expression.node;

import expression.analysis.*;

@SuppressWarnings("nls")
public final class ATermoLogicoTermoLogico extends PTermoLogico
{
    private PParenteses _parenteses_;
    private PSinalLogicoE _sinalLogicoE_;
    private PParenteses2 _parenteses2_;

    public ATermoLogicoTermoLogico()
    {
        // Constructor
    }

    public ATermoLogicoTermoLogico(
        @SuppressWarnings("hiding") PParenteses _parenteses_,
        @SuppressWarnings("hiding") PSinalLogicoE _sinalLogicoE_,
        @SuppressWarnings("hiding") PParenteses2 _parenteses2_)
    {
        // Constructor
        setParenteses(_parenteses_);

        setSinalLogicoE(_sinalLogicoE_);

        setParenteses2(_parenteses2_);

    }

    @Override
    public Object clone()
    {
        return new ATermoLogicoTermoLogico(
            cloneNode(this._parenteses_),
            cloneNode(this._sinalLogicoE_),
            cloneNode(this._parenteses2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATermoLogicoTermoLogico(this);
    }

    public PParenteses getParenteses()
    {
        return this._parenteses_;
    }

    public void setParenteses(PParenteses node)
    {
        if(this._parenteses_ != null)
        {
            this._parenteses_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parenteses_ = node;
    }

    public PSinalLogicoE getSinalLogicoE()
    {
        return this._sinalLogicoE_;
    }

    public void setSinalLogicoE(PSinalLogicoE node)
    {
        if(this._sinalLogicoE_ != null)
        {
            this._sinalLogicoE_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sinalLogicoE_ = node;
    }

    public PParenteses2 getParenteses2()
    {
        return this._parenteses2_;
    }

    public void setParenteses2(PParenteses2 node)
    {
        if(this._parenteses2_ != null)
        {
            this._parenteses2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parenteses2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parenteses_)
            + toString(this._sinalLogicoE_)
            + toString(this._parenteses2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parenteses_ == child)
        {
            this._parenteses_ = null;
            return;
        }

        if(this._sinalLogicoE_ == child)
        {
            this._sinalLogicoE_ = null;
            return;
        }

        if(this._parenteses2_ == child)
        {
            this._parenteses2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._parenteses_ == oldChild)
        {
            setParenteses((PParenteses) newChild);
            return;
        }

        if(this._sinalLogicoE_ == oldChild)
        {
            setSinalLogicoE((PSinalLogicoE) newChild);
            return;
        }

        if(this._parenteses2_ == oldChild)
        {
            setParenteses2((PParenteses2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
