/* This file was generated by SableCC (http://www.sablecc.org/). */

package expression.node;

import expression.analysis.*;

@SuppressWarnings("nls")
public final class ATermoLogicoTermoLogico extends PTermoLogico
{
    private PTermoLogico _termoLogico_;
    private PSinalLogicoE _sinalLogicoE_;
    private PExpressaoRelac _expressaoRelac_;

    public ATermoLogicoTermoLogico()
    {
        // Constructor
    }

    public ATermoLogicoTermoLogico(
        @SuppressWarnings("hiding") PTermoLogico _termoLogico_,
        @SuppressWarnings("hiding") PSinalLogicoE _sinalLogicoE_,
        @SuppressWarnings("hiding") PExpressaoRelac _expressaoRelac_)
    {
        // Constructor
        setTermoLogico(_termoLogico_);

        setSinalLogicoE(_sinalLogicoE_);

        setExpressaoRelac(_expressaoRelac_);

    }

    @Override
    public Object clone()
    {
        return new ATermoLogicoTermoLogico(
            cloneNode(this._termoLogico_),
            cloneNode(this._sinalLogicoE_),
            cloneNode(this._expressaoRelac_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATermoLogicoTermoLogico(this);
    }

    public PTermoLogico getTermoLogico()
    {
        return this._termoLogico_;
    }

    public void setTermoLogico(PTermoLogico node)
    {
        if(this._termoLogico_ != null)
        {
            this._termoLogico_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoLogico_ = node;
    }

    public PSinalLogicoE getSinalLogicoE()
    {
        return this._sinalLogicoE_;
    }

    public void setSinalLogicoE(PSinalLogicoE node)
    {
        if(this._sinalLogicoE_ != null)
        {
            this._sinalLogicoE_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sinalLogicoE_ = node;
    }

    public PExpressaoRelac getExpressaoRelac()
    {
        return this._expressaoRelac_;
    }

    public void setExpressaoRelac(PExpressaoRelac node)
    {
        if(this._expressaoRelac_ != null)
        {
            this._expressaoRelac_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoRelac_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._termoLogico_)
            + toString(this._sinalLogicoE_)
            + toString(this._expressaoRelac_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._termoLogico_ == child)
        {
            this._termoLogico_ = null;
            return;
        }

        if(this._sinalLogicoE_ == child)
        {
            this._sinalLogicoE_ = null;
            return;
        }

        if(this._expressaoRelac_ == child)
        {
            this._expressaoRelac_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._termoLogico_ == oldChild)
        {
            setTermoLogico((PTermoLogico) newChild);
            return;
        }

        if(this._sinalLogicoE_ == oldChild)
        {
            setSinalLogicoE((PSinalLogicoE) newChild);
            return;
        }

        if(this._expressaoRelac_ == oldChild)
        {
            setExpressaoRelac((PExpressaoRelac) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
